language: java

# Jackson 3.x is java 8 only so:
jdk:
  - openjdk8

# Below this line is configuration for deploying to the Sonatype OSS repo
# https://knowm.org/configure-travis-ci-to-deploy-snapshots/
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
after_success: "mvn deploy --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "VKqTLEyT46NsQeFUvdUxNDhnSGcAc7BTvYbvcsMQEuC3Lzkfw3JPSbZvIcBrrkhb85h9nzoGu8pRKIyjgxBN+qdrCKAudI3ql/tCDGTiRe+fiuLDh03++F9VL2mMZlT2ErKSVEbo6h2+t7tgfP4MRJbgdcTfiwg4qOUuArGrGjQ="
    - secure: "UlCOw7kMZFpxeG7aPXhhauI3f+iujnGRA5FlV01x36ncXMBJudrAJ8DccRir1f5r0XdMnVt1wZOWSmkG0k/y9E2SPPxjRoC7nG3HPLcEJZRPhbGXTAq190+cMdMtwb9PIS7BrCFEzPHMmfYnjunR2m5vjDUGLf9b+P7xTbhvlG8="

