language: java
jdk:
  - openjdk6

# Below this line is configuration for deploying to the Sonatype OSS repo
# http://blog.xeiam.com/2013/05/configure-travis-ci-to-deploy-snapshots.html
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "mvn deploy --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - master

env:
  global:
  - secure: "RVPjznbP+QLO5NddJylG3gL/8MBQw2r4SpZatf7gPItYVlTVtnPe5JIpkIoI6TcAp9EEmjfofOZSrhqEyVqPMCMyKRPizIK6cyR0hSFWhKTY0+oEt1ftcsMBjfeuZ4im8rbIyonUe1mQYNekVPLvrYxdmBOaAiWsNwpvMGlOl+w="
  - secure: "qshcrAvcqbPB/y7MSMVUYPgMr5AthzHqflA8edbmnMvIToxS3iHqh+zcp2m1UCFYc12QTZip8H8jjkfkZG1XekPWKyh7Tstu7yZcYLQZjpHpDjW/3x5jq53FRqNSucgcsqPvDwUbJciwgXlIqRaADDRgsLONOETPChzeuz8qPCY="

